In [1]:
# import sys
# sys.setrecursionlimit(10000)
from time import time
import numpy as np
from Tree.tree_builder import tree_builder
from Tree.tree_values import TreeValues
from Tree.strategy_filling import strategy_filling
from Tree.tree_visualizer import tree_visualizer
from Tree.tree_cfr import TreeCFR
from helper_classes import TreeParams, Node
from Game.card_to_string_conversion import card_to_string
from Game.card_tools import card_tools
from Settings.constants import constants
from Settings.arguments import arguments
from Settings.game_settings import game_settings

In [2]:
PC = constants.players_count
CC = game_settings.card_count

# Tree Build

In [3]:
# params = TreeParams()
# params.limit_to_street = True
# first_node = Node()
# first_node.board = np.zeros([], dtype=int)
# first_node.street = 1
# first_node.current_player = constants.players.P1
# first_node.bets = np.array([arguments.ante, arguments.ante], dtype=int)
# params.root_node = first_node
# params.limit_to_street = True

# root = tree_builder.build_tree(params)
# strategy_filling.fill_uniform(root)

In [4]:
# tree_visualizer.draw_tree(root, size='30,10', show_vars=True)

In [5]:
# params = TreeParams()
# params.root_node = Node()
# params.root_node.board = card_to_string.string_to_board('Ks')
# params.root_node.street = 2
# params.root_node.current_player = constants.players.P2
# params.root_node.bets = np.array([300, 300])
# params.limit_to_street = False
# root = tree_builder.build_tree(params)
# tree_visualizer.draw_tree(root, size='20,10')

# Exploitability

In [6]:
# params = TreeParams()

# params.root_node = Node()
# params.root_node.board = card_to_string.string_to_board('')
# params.root_node.street = 1
# params.root_node.current_player = constants.players.P1
# params.root_node.bets = np.array([100, 100])

# tree = tree_builder.build_tree(params)

# tree_values = TreeValues()

# starting_ranges = np.zeros([PC,CC], dtype=arguments.dtype)
# starting_ranges[0] = card_tools.get_uniform_range(params.root_node.board)
# starting_ranges[1] = card_tools.get_uniform_range(params.root_node.board)

# tree_values.compute_values(tree, starting_ranges)

# print('Exploitability: ' + str(tree.exploitability) + ' [chips]' )

# CFR

In [7]:
# params = TreeParams()

# params.root_node = Node()
# params.root_node.board = card_to_string.string_to_board('')
# params.root_node.street = 1
# params.root_node.current_player = constants.players.P1
# params.root_node.bets = np.array([100, 100])

# tree = tree_builder.build_tree(params)

# starting_ranges = np.zeros([PC,CC], dtype=arguments.dtype)
# starting_ranges[0] = card_tools.get_uniform_range(params.root_node.board)
# starting_ranges[1] = card_tools.get_uniform_range(params.root_node.board)

# t0 = time()
# tree_cfr = TreeCFR()
# %lprun -f tree_cfr.cfrs_iter_dfs tree_cfr.run_cfr(tree, starting_ranges)
# print('Took time: {} for {} iters'.format(time()-t0, arguments.cfr_iters))

# tree_values = TreeValues()
# tree_values.compute_values(tree, starting_ranges)

# print('Exploitability: ' + str(tree.exploitability) + ' [chips]' )

# Card and Range Generator

In [8]:
from DataGeneration.random_card_generator import card_generator
card_generator.generate_cards(6)

array([5, 1, 3, 2, 4, 0])

In [20]:
from DataGeneration.range_generator import RangeGenerator
r = RangeGenerator()
board = np.zeros([])
r.set_board(board)
BS,CC = 10,6
ranges = np.zeros([BS,CC])
r.generate_range(ranges)
print(np.array2string(ranges, suppress_small=True, precision=2))
print(np.array2string(np.sum(ranges, axis=1, keepdims=True), suppress_small=True, precision=2))

[[0.21 0.38 0.16 0.02 0.   0.23]
 [0.08 0.05 0.09 0.61 0.05 0.12]
 [0.22 0.5  0.09 0.07 0.1  0.03]
 [0.08 0.12 0.74 0.   0.02 0.03]
 [0.02 0.   0.04 0.2  0.02 0.72]
 [0.09 0.1  0.55 0.03 0.01 0.22]
 [0.   0.05 0.06 0.25 0.09 0.53]
 [0.06 0.32 0.28 0.03 0.2  0.1 ]
 [0.13 0.13 0.01 0.44 0.1  0.2 ]
 [0.01 0.08 0.62 0.02 0.17 0.1 ]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
