In [1]:
import sys
# # sys.setrecursionlimit(10000)
import os
sys.path.append( os.getcwd() )
os.chdir('..')
from tqdm import tqdm

In [2]:
from time import time
import numpy as np
from Tree.tree_builder import tree_builder
from Tree.tree_values import TreeValues
from Tree.tree_visualizer import tree_visualizer
from Tree.tree_cfr import TreeCFR
from helper_classes import TreeParams, Node
from Game.card_to_string_conversion import card_to_string
from Game.card_tools import card_tools
from Game.card_combinations import card_combinations
from Settings.constants import constants
from Settings.arguments import arguments
from NeuralNetwork.value_nn import ValueNn
from NeuralNetwork.metrics import BasicHuberLoss
from TerminalEquity.terminal_equity import TerminalEquity
from TerminalEquity.evaluator import evaluator
from Lookahead.resolving import Resolving
from DataGeneration.range_generator import RangeGenerator
from Player.continual_resolving import ContinualResolving

In [3]:
PC = constants.players_count
CC = constants.card_count
HC = constants.hand_count
P1 = constants.players.P1
P2 = constants.players.P2
sb = arguments.sb
bb = arguments.bb

In [4]:
%load_ext line_profiler
def asd(boards):
    for board in boards:
        card_tools.get_possible_hand_indexes(board)
boards = card_tools.get_next_round_boards(card_to_string.string_to_board(''))
# %lprun -f card_tools.get_possible_hand_indexes asd(boards)
# %timeit asd(boards)

In [5]:
deepstack = ContinualResolving()

In [6]:
# tree_visualizer.draw_tree( deepstack.resolving.lookahead_tree )

In [7]:
deepstack.starting_cfvs_as_P1

array([ 43.083977,  45.523643,  44.322838, ..., 216.45993 , 217.055   ,
       218.90306 ], dtype=float32)

In [8]:
deepstack.start_new_hand('2c','2h',player_is_small_blind=False)

In [9]:
deepstack.player_range.shape

(1326,)

In [10]:
a = deepstack.compute_action('', player_bet=100, opponent_bet=300)

created node: bets: 300.0/100.0 num_bets: 0 street: 1 i: 1 board: 0
num_transition_nodes: [ 300.  900. 2700. 8100.]
{-1: 0, 900: 1, 20000: 2}


100%|████████████████████████████████████████████████████████████████████████████| 1000/1000 [1:01:41<00:00,  7.47s/it]


[9.9919064e-15 9.9919248e-01 7.2770490e-04 7.9793565e-05]
[   -2    -1   900 20000]
strat: [0.    0.999 0.001 0.   ], bets: [   -2    -1   900 20000], sampled_bet: -1


In [11]:
deepstack.opponent_cfvs

array([ 65.44637,  66.19749,  65.7249 , ..., 187.35196, 187.20956,
       186.86998], dtype=float32)

In [ ]:
a = deepstack.compute_action('', player_bet=, opponent_bet=100)

In [11]:
1/1326

0.0007541478129713424

In [ ]:
card_combinations.choose(52-4,1)

In [ ]:
card_tools.get_last_round_boards(card_to_string.string_to_board('2c3c4c')).shape